### ISSUE TITLE
Tracking issue for PrintAST queries in supported languages

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#505]
This is a tracking issue for all supported languages to implement the `PrintAST` functionality so that the VS Code extension can view ASTs for the files written in the language.

See #476 for the parent issue. In order to provide the feature, supported languages will need to implement a `graph` query that conforms to the required format. See the description of [PrintAST for C++](https://github.com/github/codeql-c-analysis-team/blob/master/wiki/PrintAST%20Implementation.md) for how the results should be formatted.

- [x] C++ (already completed)
- [x] C#  https://github.com/github/codeql/issues/3957
- [x] Go https://github.com/github/codeql-go/issues/260
- [x] Java https://github.com/github/codeql/issues/3955
- [x] JavaScript https://github.com/github/codeql/issues/3954
- [x] Python https://github.com/github/codeql/issues/3956

Note that #492 is not yet released to master. I will put the implementation behind a feature flag before releasing.

**Comment by shati-patel** [comment]
Hi @aeisenberg! 👋🏼 
Do you have an idea when the AST viewer is likely to be generally available for all languages? I've had a little play around with the feature flag, but just checking when we need to pick up the docs work in earnest 📝

**Comment by aeisenberg** [comment]
Due to other priorities, I haven't been able to push forward with this task recently. Before the feature flag is removed, I'd like it to be available for most languages. I'll probably be able to pick this up again in a couple of weeks.

**Comment by shati-patel** [comment]
> Due to other priorities, I haven't been able to push forward with this task recently. Before the feature flag is removed, I'd like it to be available for most languages. I'll probably be able to pick this up again in a couple of weeks. I'll mention here when I do, so keep watching this issue.

That's good to know, thank you! 😊
